### ISSUE TITLE
Make this subtask

### ISSUE THREAD

**Issue by Fulkin** [Fulkin/liveProject#1]
Make first subtask

**Comment by Fulkin** [comment]
- [x] Make first subtask
- [x] Make other subtask
- [x] Make third subtask
